name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  update-draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@72967cdc98ddd3160f1fc3dff619de365e137dd0 # v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
